version: '3'

services:
  mysqld:
    image: mysql:latest
    container_name: fitnesstracking1
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

  bima-app:
    image: fitnesstracking1
    ports:
      - "8081:8081"
    depends_on:
      - mysqld
    environment:
      MYSQL_HOST: mysqld
      

volumes:
  mysql-data:
