version: '3'

services:
  mysqld:
    image: mysql:latest
    container_name: fitnesstracking
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

  fitness-tracking:
    image: myfitnesstracking
    ports:
      - "8081:8081" 
    depends_on:
      - mysqld
    environment:
      MYSQL_HOST: mysqld
      

volumes:
  mysql-data:
