---
- name: Deploy Fitnesstracking application
  hosts: all
  become: true
  tasks:
    - name: Recursively change the ownership
      file:
        path: /home/asule/Fitness
        state: directory
        recurse: yes
        owner: jonathan
      
    - name: Copy Docker Compose File
      copy:
        src: /home/jonathan/Desktop/java EE/FitnessTracking/docker-compose.yml
        dest: /home/asule/Fitness/docker-compose.yml
      become: true

    - name: Orchestrate using docker compose
      command: docker-compose -f /home/asule/Fitness/docker-compose.yml up -d   
