- name: Deploy Fitnesstracking application
  hosts: all
  become: true
  tasks:
    - name: Recursively change the ownership
      file:
        path: /home/asule/Fitness
        state: directory
        recurse: yes
        owner: jonathan
        group: jonathan

    - name: Copy Docker Compose file
      copy:
        src: "/home/jonathan/Desktop/java EE/FitnessTracking/docker-compose.yml"  # Adjusted the path to escape spaces
        dest: /home/asule/Fitness/docker-compose.yml
        owner: jonathan
        group: jonathan
        mode: 755

    - name: Deploy Fitnesstracking application
      command: docker-compose -f /home/asule/Fitness/docker-compose.yml up -d
